import { SimulationMetadata } from '../types/simulation';

export const SIMULATION_REGISTRY: SimulationMetadata[] = [
  // ==========================================
  // MATHEMATICS (1-5 Implemented + Planned)
  // ==========================================
  {
    id: 'math-linear-equation',
    title: 'Linear Equations & Slope Analysis',
    subject: 'mathematics',
    topic: 'Algebra & Functions',
    difficulty: 'Beginner',
    estimatedMinutes: 8,
    description: 'Explore slope (m) and y-intercept (c) in real-time. Visualize rise-over-run triangles, calculate coordinate intersections, and observe dynamic equation formulation.',
    learningObjectives: [
      'Understand how slope (m) dictates line steepness and direction (positive vs negative)',
      'Discover the geometric meaning of the y-intercept (0, c)',
      'Calculate x-intercept roots when y = 0',
      'Relate Cartesian coordinates to standard equation form y = mx + c',
    ],
    prerequisites: ['Basic Cartesian (x, y) coordinates', 'Arithmetic operations'],
    explanation: {
      concept: 'A linear equation represents a straight line relationship between two variables where each degree is 1.',
      whatWeChange: 'Slope (m) adjusting steepness, and y-intercept (c) translating the line vertically.',
      whatHappens: 'The line rotates about (0, c) when m changes, and translates parallel to itself when c changes.',
      whyItHappens: 'Slope is defined as change in y divided by change in x (Δy/Δx). Adding c shifts every output point by c.',
      formula: 'y = mx + c  |  Root x₀ = -c / m (for m ≠ 0)',
      takeaway: 'Any constant rate of change in physics or finance is geometrically a linear slope.',
    },
    controls: [
      { id: 'slope', label: 'Slope (m)', min: -5, max: 5, step: 0.25, defaultValue: 1.5, unit: '' },
      { id: 'intercept', label: 'Y-Intercept (c)', min: -10, max: 10, step: 0.5, defaultValue: 2, unit: '' },
    ],
    questions: [
      {
        id: 'q1',
        question: 'If the slope (m) is negative, what happens to the line as x increases from left to right?',
        options: ['The line slants downwards', 'The line slants upwards', 'The line remains horizontal', 'The line becomes vertical'],
        correctIndex: 0,
        explanation: 'A negative slope means y decreases as x increases (Δy/Δx < 0), causing the line to slant downwards.',
      },
      {
        id: 'q2',
        question: 'What is the x-intercept of the line when m = 2 and c = -6?',
        options: ['x = -3', 'x = 3', 'x = 6', 'x = -6'],
        correctIndex: 1,
        explanation: 'At the x-intercept, y = 0: 0 = 2x - 6 → 2x = 6 → x = 3.',
      },
      {
        id: 'q3',
        question: 'What occurs geometrically when the slope m is set to exactly 0?',
        options: ['The line is parallel to the y-axis', 'The line is a horizontal line parallel to the x-axis at y = c', 'The line disappears', 'The line forms a 45-degree angle'],
        correctIndex: 1,
        explanation: 'When m = 0, y = 0x + c = c for all x, which is a flat horizontal line at constant height c.',
      },
    ],
    recommendedNextTopics: ['math-quadratic', 'math-calculus-derivative'],
    isImplemented: true,
  },
  {
    id: 'math-quadratic',
    title: 'Quadratic Equation Visualizer',
    subject: 'mathematics',
    topic: 'Quadratic Functions',
    difficulty: 'Intermediate',
    estimatedMinutes: 12,
    description: 'Manipulate polynomial coefficients a, b, and c to explore parabolas, vertex shifts, discriminant (Δ = b² - 4ac), and real vs complex roots.',
    learningObjectives: [
      'Observe how the coefficient "a" determines parabolic concavity (open upward vs downward)',
      'Calculate the vertex (h, k) using h = -b / (2a)',
      'Determine the number and nature of roots using the discriminant Δ',
      'Analyze the axis of symmetry x = -b / 2a',
    ],
    prerequisites: ['Linear equations', 'Square root arithmetic'],
    explanation: {
      concept: 'A quadratic function is a second-order polynomial producing a U-shaped curve known as a parabola.',
      whatWeChange: 'Coefficients a (curvature), b (linear shear/shift), and c (vertical translation).',
      whatHappens: 'When a > 0 the parabola opens upward (minimum vertex); when a < 0 it opens downward (maximum vertex).',
      whyItHappens: 'The squared term x² dominates large values. The discriminant determines whether the curve crosses the x-axis.',
      formula: 'y = ax² + bx + c  |  Δ = b² - 4ac  |  x = (-b ± √Δ) / 2a',
      takeaway: 'Discriminant > 0 produces 2 distinct real roots; = 0 produces 1 repeated root; < 0 produces complex conjugate roots.',
    },
    controls: [
      { id: 'a', label: 'Coefficient a', min: -3, max: 3, step: 0.1, defaultValue: 1, unit: '' },
      { id: 'b', label: 'Coefficient b', min: -6, max: 6, step: 0.2, defaultValue: -2, unit: '' },
      { id: 'c', label: 'Coefficient c', min: -8, max: 8, step: 0.5, defaultValue: -3, unit: '' },
    ],
    questions: [
      {
        id: 'q1',
        question: 'What is the nature of the roots if the discriminant Δ is strictly negative (Δ < 0)?',
        options: ['Two distinct real roots', 'One real repeated root', 'No real roots (two complex conjugate roots)', 'Infinitely many roots'],
        correctIndex: 2,
        explanation: 'Because taking the square root of a negative number produces imaginary values, Δ < 0 means no intersection with the real x-axis.',
      },
      {
        id: 'q2',
        question: 'Where is the x-coordinate of the vertex located for y = ax² + bx + c?',
        options: ['x = -b / a', 'x = -b / (2a)', 'x = c / a', 'x = -2b / a'],
        correctIndex: 1,
        explanation: 'By completing the square or taking the derivative 2ax + b = 0, the vertex is at x = -b / (2a).',
      },
      {
        id: 'q3',
        question: 'For a = 1, b = -2, c = -3, what are the roots where y = 0?',
        options: ['x = 3 and x = -1', 'x = 2 and x = -3', 'x = 1 and x = -3', 'x = 0 and x = 3'],
        correctIndex: 0,
        explanation: 'Factoring: (x - 3)(x + 1) = 0 yields roots x = 3 and x = -1. Discriminant Δ = 4 - 4(1)(-3) = 16 > 0.',
      },
    ],
    recommendedNextTopics: ['math-calculus-derivative', 'physics-projectile'],
    isImplemented: true,
  },
  {
    id: 'math-trig-wave',
    title: 'Trigonometric Wave & Phase Dynamics',
    subject: 'mathematics',
    topic: 'Trigonometry',
    difficulty: 'Intermediate',
    estimatedMinutes: 10,
    description: 'Interactive sine and cosine wave synthesis. Control amplitude A, angular frequency B, phase shift C, and vertical offset D to see harmonic motion.',
    learningObjectives: [
      'Understand how amplitude A affects peak height and acoustic/optical energy',
      'Discover period T = 2π / B and its inverse relationship with frequency',
      'Visualize phase shift (C / B) sliding the wave horizontally along the time/space axis',
      'Examine the fundamental identity sin²(θ) + cos²(θ) = 1',
    ],
    prerequisites: ['Radian measurement', 'Unit circle basics'],
    explanation: {
      concept: 'Trigonometric waves model cyclic phenomena like light, alternating electric current, and acoustic vibrations.',
      whatWeChange: 'Amplitude (A), Frequency factor (B), Phase horizontal shift (C), and Vertical offset (D).',
      whatHappens: 'Amplitude stretches peaks; B compresses or elongates the wave period; C delays or advances the wave crests.',
      whyItHappens: 'Sine maps the vertical coordinate of a rotating point around the unit circle as angle increases linearly.',
      formula: 'y = A · sin(B · x - C) + D  |  Period T = 2π / |B|',
      takeaway: 'Fourier analysis demonstrates all periodic signals are combinations of fundamental sinusoids.',
    },
    controls: [
      { id: 'amplitude', label: 'Amplitude (A)', min: 0.2, max: 4, step: 0.1, defaultValue: 2, unit: '' },
      { id: 'frequency', label: 'Frequency (B)', min: 0.5, max: 5, step: 0.25, defaultValue: 1, unit: 'rad/s' },
      { id: 'phase', label: 'Phase Shift (C)', min: -3.14, max: 3.14, step: 0.1, defaultValue: 0, unit: 'rad' },
      { id: 'offset', label: 'Vertical Offset (D)', min: -2, max: 2, step: 0.2, defaultValue: 0, unit: '' },
    ],
    questions: [
      {
        id: 'q1',
        question: 'If the frequency factor B increases from 1 to 2, what happens to the period of the wave?',
        options: ['The period doubles', 'The period is halved (cut by 50%)', 'The period remains unchanged', 'The amplitude doubles'],
        correctIndex: 1,
        explanation: 'Period T = 2π / B. If B doubles, the period T becomes 2π / (2B) = T/2, oscillating twice as quickly.',
      },
      {
        id: 'q2',
        question: 'What is the maximum peak-to-trough height (total span) of a wave with Amplitude A = 3?',
        options: ['3', '6', '9', '1.5'],
        correctIndex: 1,
        explanation: 'The wave reaches +A at peak and -A at trough, so the peak-to-trough distance is 2A = 2 × 3 = 6.',
      },
      {
        id: 'q3',
        question: 'A phase shift of C = π/2 radians turns a sine wave into which trigonometric function?',
        options: ['Cosine (or -Cosine depending on sign)', 'Tangent', 'Secant', 'Exponential'],
        correctIndex: 0,
        explanation: 'By the phase co-function identity, sin(x + π/2) = cos(x).',
      },
    ],
    recommendedNextTopics: ['physics-wave-motion', 'physics-pendulum'],
    isImplemented: true,
  },
  {
    id: 'math-probability',
    title: 'Probability & Law of Large Numbers',
    subject: 'mathematics',
    topic: 'Probability & Statistics',
    difficulty: 'Beginner',
    estimatedMinutes: 10,
    description: 'Run automated Monte Carlo experiment trials for coin tosses, dice rolls, and normal distributions. Watch empirical frequency converge to theoretical probability.',
    learningObjectives: [
      'Differentiate between theoretical probability and empirical experimental frequency',
      'Witness the Law of Large Numbers in action as trial count N reaches thousands',
      'Analyze sample variance and standard error reduction proportional to 1/√N',
      'Interpret relative frequency histograms and cumulative probability graphs',
    ],
    prerequisites: ['Basic fractions and percentages'],
    explanation: {
      concept: 'Probability quantifies the likelihood of events. Random variation dominates small samples, but converges with large sample sizes.',
      whatWeChange: 'Number of experiment trials (10 to 5,000) and fair vs biased coin/dice odds.',
      whatHappens: 'With 10 trials, heads may be 30% or 70%. With 2,000 trials, the ratio consistently stabilizes near the theoretical 50.0%.',
      whyItHappens: 'According to Bernoulli’s Law of Large Numbers, the sample average converges almost surely to the expected value.',
      formula: 'P(E) = n(E) / n(S)  |  Standard Error SE = √(p(1-p)/N)',
      takeaway: 'Statistical certainty emerges from aggregated random events — the foundation of quantum physics and data science.',
    },
    controls: [
      { id: 'trials', label: 'Number of Trials (N)', min: 20, max: 2000, step: 20, defaultValue: 200, unit: 'trials' },
      { id: 'bias', label: 'Theoretical Probability p', min: 0.1, max: 0.9, step: 0.05, defaultValue: 0.5, unit: '' },
    ],
    questions: [
      {
        id: 'q1',
        question: 'According to the Law of Large Numbers, what happens to experimental probability as the number of trials increases?',
        options: ['It diverges wildly', 'It converges closer and closer to theoretical probability', 'It always equals 100%', 'It resets to zero'],
        correctIndex: 1,
        explanation: 'As sample size N → ∞, the sample mean converges in probability to the expected theoretical probability.',
      },
      {
        id: 'q2',
        question: 'If you flip a fair coin 10 times and get 8 heads, is the coin definitely unfair?',
        options: ['Yes, exactly 5 heads must always appear', 'No, in small sample sizes random statistical fluctuation is common', 'Yes, math laws were violated', 'No, because tails will never occur'],
        correctIndex: 1,
        explanation: 'With small N = 10, binomial variance is high. Getting 8 heads has a probability of ~4.4%, which is an ordinary random deviation.',
      },
      {
        id: 'q3',
        question: 'How does the standard error of the sample proportion scale with the number of trials N?',
        options: ['It decreases inversely with the square root of N (1/√N)', 'It grows linearly with N', 'It is constant regardless of N', 'It doubles with N'],
        correctIndex: 0,
        explanation: 'Standard error = √(p(1-p)/N). Quadrupling the trials (4N) cuts the standard error in half.',
      },
    ],
    recommendedNextTopics: ['math-statistics-distribution', 'physics-collision'],
    isImplemented: true,
  },
  {
    id: 'math-calculus-derivative',
    title: 'Calculus: Derivatives & Instantaneous Change',
    subject: 'mathematics',
    topic: 'Calculus & Analysis',
    difficulty: 'Advanced',
    estimatedMinutes: 14,
    description: 'Transform a secant line into a tangent line as step size Δx approaches zero. Visualize instantaneous velocity, gradients, and area under the curve.',
    learningObjectives: [
      'Understand the limit definition of a derivative as secant step Δx → 0',
      'Observe that the derivative f’(x) represents the slope of the tangent line at any point',
      'Detect local extrema where the derivative equals zero (horizontal tangent)',
      'Explore numerical differentiation and Riemann sum integration',
    ],
    prerequisites: ['Function notation f(x)', 'Slope of a line'],
    explanation: {
      concept: 'Calculus describes continuous rates of change. The derivative is the instantaneous slope at an infinitesimal point.',
      whatWeChange: 'Point of interest x₀, secant step size Δx, and polynomial function curvature.',
      whatHappens: 'As Δx shrinks from 2.0 to 0.001, the average rate of change secant line locks onto the exact tangent line.',
      whyItHappens: 'The limit of [f(x + Δx) - f(x)] / Δx as Δx → 0 eliminates the finite interval, revealing the exact instantaneous gradient.',
      formula: "f'(x) = lim(Δx→0) [f(x + Δx) - f(x)] / Δx  |  Tangent: y - y₀ = m(x - x₀)",
      takeaway: 'Derivative tells us the speed and direction of change at this exact split-second.',
    },
    controls: [
      { id: 'x0', label: 'Point x₀', min: -3, max: 3, step: 0.1, defaultValue: 1, unit: '' },
      { id: 'deltaX', label: 'Secant Step Δx', min: 0.05, max: 2, step: 0.05, defaultValue: 0.8, unit: '' },
      { id: 'power', label: 'Function Degree n in xⁿ', min: 1, max: 3, step: 1, defaultValue: 2, unit: '' },
    ],
    questions: [
      {
        id: 'q1',
        question: 'What is the derivative of f(x) = x² at x = 3?',
        options: ['3', '6', '9', '2'],
        correctIndex: 1,
        explanation: "By the power rule, d/dx(x²) = 2x. At x = 3, f'(3) = 2(3) = 6.",
      },
      {
        id: 'q2',
        question: 'What geometric feature does a function have at points where f’(x) = 0?',
        options: ['A vertical asymptote', 'A horizontal tangent line (local maximum, minimum, or inflection)', 'A discontinuity', 'An intersection with the origin'],
        correctIndex: 1,
        explanation: 'Slope m = 0 represents a flat horizontal tangent line, indicating stationary points like peaks and valleys.',
      },
      {
        id: 'q3',
        question: 'What occurs to the secant line slope as the distance Δx between two points approaches 0?',
        options: ['It becomes undefined', 'It becomes the slope of the tangent line (instantaneous derivative)', 'It always equals 1', 'It flips upside down'],
        correctIndex: 1,
        explanation: 'The limit of the secant slopes as Δx approaches zero is by definition the tangent slope f’(x₀).',
      },
    ],
    recommendedNextTopics: ['physics-projectile', 'physics-spring-mass'],
    isImplemented: true,
  },

  // ==========================================
  // PHYSICS (1-5 Implemented + Planned)
  // ==========================================
  {
    id: 'physics-ohms-law',
    title: "Ohm's Law & Circuit Dynamics",
    subject: 'physics',
    topic: 'Electricity & Circuits',
    difficulty: 'Beginner',
    estimatedMinutes: 8,
    description: 'Adjust DC voltage and circuit resistance to observe electron current flow, incandescent filament glow intensity, and electrical power dissipation.',
    learningObjectives: [
      'Verify Ohm’s Law relationship I = V / R with real-time numeric calculations',
      'Visualize electron drift velocity and current flow proportional to voltage',
      'Calculate electrical power dissipation P = V · I = I²R',
      'Interpret resistor color code representations and circuit safety thresholds',
    ],
    prerequisites: ['Basic units: Volts, Amperes, Ohms'],
    explanation: {
      concept: "Ohm's law states that current through a conductor between two points is directly proportional to the voltage and inversely proportional to resistance.",
      whatWeChange: 'Voltage source V (volts) and total circuit resistance R (ohms).',
      whatHappens: 'Current increases with higher voltage; current decreases with higher resistance. Filament glow matches power output.',
      whyItHappens: 'Voltage acts as electrical pressure driving free conduction electrons, while resistance represents scattering collisions.',
      formula: 'I = V / R  |  Power P = V · I = V² / R',
      takeaway: 'Doubling voltage doubles current; doubling resistance cuts current in half.',
    },
    controls: [
      { id: 'voltage', label: 'Voltage (V)', min: 1, max: 24, step: 0.5, defaultValue: 12, unit: 'V' },
      { id: 'resistance', label: 'Resistance (R)', min: 2, max: 100, step: 1, defaultValue: 20, unit: 'Ω' },
    ],
    questions: [
      {
        id: 'q1',
        question: "If a 12V battery is connected to a 4Ω resistor, what is the electric current according to Ohm's Law?",
        options: ['48 A', '3 A', '0.33 A', '16 A'],
        correctIndex: 1,
        explanation: 'I = V / R = 12 V / 4 Ω = 3.0 Amperes.',
      },
      {
        id: 'q2',
        question: 'If resistance is kept constant and the applied voltage is tripled, what happens to the power dissipated (P = V²/R)?',
        options: ['It triples', 'It increases by 9 times (3²)', 'It remains constant', 'It is cut by one third'],
        correctIndex: 1,
        explanation: 'Power scales with voltage squared: (3V)² / R = 9(V²/R).',
      },
      {
        id: 'q3',
        question: 'What happens to the current in a circuit if resistance approaches zero (a short circuit)?',
        options: ['Current approaches zero', 'Current spikes toward infinity, causing thermal overload', 'Voltage drops to zero instantly', 'Resistance automatically adjusts'],
        correctIndex: 1,
        explanation: 'As R → 0, I = V / R approaches infinity, leading to dangerous heat generation and blown fuses.',
      },
    ],
    recommendedNextTopics: ['physics-series-circuit', 'physics-capacitor'],
    isImplemented: true,
  },
  {
    id: 'physics-projectile',
    title: 'Kinematic Projectile Motion',
    subject: 'physics',
    topic: 'Classical Mechanics',
    difficulty: 'Intermediate',
    estimatedMinutes: 12,
    description: 'Launch projectiles in a 2D gravitational field. Adjust launch speed, elevation angle, gravitational acceleration, and observe parabolic trajectory metrics.',
    learningObjectives: [
      'Decompose 2D velocity vectors into independent horizontal (vx) and vertical (vy) components',
      'Calculate maximum height H = (v₀ sinθ)² / (2g)',
      'Calculate total horizontal range R = (v₀² sin2θ) / g',
      'Demonstrate that 45 degrees yields maximum theoretical range in a vacuum',
    ],
    prerequisites: ['Trigonometry sine and cosine', 'Newtonian acceleration'],
    explanation: {
      concept: 'A projectile experiences constant downward acceleration due to gravity while moving horizontally at constant velocity (neglecting air drag).',
      whatWeChange: 'Initial launch speed v₀ (m/s), angle θ (degrees), and planet gravity g (m/s²).',
      whatHappens: 'Horizontal motion remains uniform (ax = 0), while vertical motion decelerates to zero at apex and accelerates back down.',
      whyItHappens: 'Gravity acts purely along the vertical y-axis, leaving the x-momentum unaffected in ideal vacuum ballistics.',
      formula: 'x(t) = v₀ cos(θ) · t  |  y(t) = v₀ sin(θ) · t - ½ g t²  |  R = v₀² sin(2θ) / g',
      takeaway: 'Orthogonal kinematic dimensions operate completely independently.',
    },
    controls: [
      { id: 'velocity', label: 'Initial Velocity (v₀)', min: 5, max: 50, step: 1, defaultValue: 25, unit: 'm/s' },
      { id: 'angle', label: 'Launch Angle (θ)', min: 10, max: 85, step: 1, defaultValue: 45, unit: '°' },
      { id: 'gravity', label: 'Gravity (g)', min: 1.62, max: 24.8, step: 0.1, defaultValue: 9.81, unit: 'm/s²' },
    ],
    questions: [
      {
        id: 'q1',
        question: 'Assuming no air resistance, which launch angle produces the maximum horizontal range on level ground?',
        options: ['30 degrees', '45 degrees', '60 degrees', '90 degrees'],
        correctIndex: 1,
        explanation: 'Range R = (v₀² sin 2θ) / g. The maximum of sin(2θ) is 1 at 2θ = 90°, which means θ = 45° maximizes range.',
      },
      {
        id: 'q2',
        question: 'At the apex (highest peak) of the trajectory, what is the vertical component of velocity (vy)?',
        options: ['Equal to initial velocity', 'Zero (0 m/s)', 'Maximum velocity', 'Negative infinity'],
        correctIndex: 1,
        explanation: 'At the exact apex, vertical upward velocity has decelerated to 0 m/s before switching direction downward.',
      },
      {
        id: 'q3',
        question: 'If you launch a projectile on the Moon where gravity is ~1.62 m/s² (1/6th of Earth), how does total flight time change?',
        options: ['Flight time increases significantly (approx 6 times longer)', 'Flight time is 6 times shorter', 'Flight time is identical', 'The projectile floats away forever'],
        correctIndex: 0,
        explanation: 'Total time T = 2 v₀ sin(θ) / g. Since g is in the denominator, lower gravity leads to substantially longer hang-time.',
      },
    ],
    recommendedNextTopics: ['physics-pendulum', 'math-quadratic'],
    isImplemented: true,
  },
  {
    id: 'physics-pendulum',
    title: 'Simple Harmonic Pendulum Oscillator',
    subject: 'physics',
    topic: 'Harmonic Motion',
    difficulty: 'Intermediate',
    estimatedMinutes: 10,
    description: 'Simulate a pendulum bob oscillating under gravity. Test string length L, gravitational field g, initial release angle, and damping air drag.',
    learningObjectives: [
      'Derive the time period formula T = 2π √(L / g) for small-angle oscillations',
      'Observe that for small angles, the pendulum period is independent of bob mass',
      'Track real-time conservation of mechanical energy (potential ↔ kinetic)',
      'Analyze phase space trajectories and damped exponential decay',
    ],
    prerequisites: ['Trigonometry', 'Gravitational potential energy'],
    explanation: {
      concept: 'A simple pendulum exhibits simple harmonic motion (SHM) where restoring torque is proportional to the sine of displacement angle.',
      whatWeChange: 'Rod length L (meters), gravity g, release angle θ₀, and damping factor.',
      whatHappens: 'Longer pendulums swing with lower frequency; higher gravity speeds up oscillation cycles.',
      whyItHappens: 'For small angles sin(θ) ≈ θ (radians). The restoring force pulls the mass toward equilibrium with acceleration -g/L · θ.',
      formula: 'Period T ≈ 2π √(L / g)  |  θ(t) = θ₀ cos(ωt) e^(-γt)  |  ω = √(g / L)',
      takeaway: 'In ideal small-angle harmonic motion, the period depends ONLY on length and gravity, never on mass.',
    },
    controls: [
      { id: 'length', label: 'String Length (L)', min: 0.5, max: 3.0, step: 0.1, defaultValue: 1.5, unit: 'm' },
      { id: 'gravity', label: 'Gravity (g)', min: 1.62, max: 20, step: 0.2, defaultValue: 9.81, unit: 'm/s²' },
      { id: 'initialAngle', label: 'Release Angle (θ₀)', min: 5, max: 60, step: 5, defaultValue: 25, unit: '°' },
      { id: 'damping', label: 'Damping Friction', min: 0, max: 0.15, step: 0.01, defaultValue: 0.02, unit: '' },
    ],
    questions: [
      {
        id: 'q1',
        question: 'What happens to the period (T) of a simple pendulum if you quadruple its length (4 × L)?',
        options: ['The period quadruples', 'The period doubles (2 × T)', 'The period is cut in half', 'The period is unchanged'],
        correctIndex: 1,
        explanation: 'Period T = 2π √(L/g). √(4L) = 2√L, so the period doubles.',
      },
      {
        id: 'q2',
        question: 'Does increasing the mass of the pendulum bob change its oscillation period in small angles?',
        options: ['Yes, heavier bobs swing faster', 'Yes, heavier bobs swing slower', 'No, the period is independent of mass', 'Only if damping is zero'],
        correctIndex: 2,
        explanation: 'In the equation of motion mg sinθ = m(L α), mass m cancels on both sides of the equation.',
      },
      {
        id: 'q3',
        question: 'At which point in the pendulum swing is kinetic energy at its absolute maximum?',
        options: ['At the highest points of release', 'At the lowest equilibrium point (bottom of the swing)', 'Halfway between peak and bottom', 'It is constant everywhere'],
        correctIndex: 1,
        explanation: 'At the bottom, potential energy is at its minimum, so all potential energy has been converted into maximum kinetic velocity.',
      },
    ],
    recommendedNextTopics: ['physics-spring-mass', 'physics-wave-motion'],
    isImplemented: true,
  },
  {
    id: 'physics-spring-mass',
    title: 'Spring-Mass Oscillator & Hooke’s Law',
    subject: 'physics',
    topic: 'Oscillations & Energy',
    difficulty: 'Intermediate',
    estimatedMinutes: 10,
    description: 'Explore Hooke’s Law (F = -kx) with an animated spring. Alter spring stiffness k, attached mass m, and damping to observe resonance and energy transformation.',
    learningObjectives: [
      'Master Hooke’s Law restorative force F = -kx and spring constant k',
      'Derive angular frequency ω = √(k / m) and natural period T = 2π √(m / k)',
      'Track potential energy E_p = ½kx² and kinetic energy E_k = ½mv²',
      'Compare underdamped, critically damped, and overdamped motion',
    ],
    prerequisites: ['Potential energy', 'Newton’s second law F = ma'],
    explanation: {
      concept: 'An elastic spring exerts a restorative force directly proportional to its displacement from equilibrium.',
      whatWeChange: 'Spring stiffness constant k (N/m), suspended mass m (kg), and initial displacement x₀.',
      whatHappens: 'A stiffer spring (high k) oscillates faster; a heavier mass (high m) oscillates slower.',
      whyItHappens: 'Acceleration a = -(k/m)x. The ratio k/m sets the natural frequency ω² of the second-order differential equation.',
      formula: 'F = -kx  |  T = 2π √(m / k)  |  Total Energy E = ½ k x_max²',
      takeaway: 'Total mechanical energy remains constant in an undamped oscillator as energy cycles between kinetic and elastic.',
    },
    controls: [
      { id: 'k', label: 'Spring Constant (k)', min: 10, max: 150, step: 5, defaultValue: 50, unit: 'N/m' },
      { id: 'mass', label: 'Mass (m)', min: 0.2, max: 5.0, step: 0.2, defaultValue: 1.5, unit: 'kg' },
      { id: 'displacement', label: 'Displacement (x₀)', min: 0.1, max: 0.8, step: 0.05, defaultValue: 0.4, unit: 'm' },
      { id: 'damping', label: 'Damping (c)', min: 0, max: 2.0, step: 0.1, defaultValue: 0.2, unit: 'N·s/m' },
    ],
    questions: [
      {
        id: 'q1',
        question: 'If you replace a spring with one that is 4 times stiffer (4k), what happens to the natural frequency of oscillation?',
        options: ['Frequency doubles', 'Frequency is halved', 'Frequency quadruples', 'Frequency does not change'],
        correctIndex: 0,
        explanation: 'Natural frequency f = (1 / 2π) √(k / m). Replacing k with 4k multiplies frequency by √4 = 2.',
      },
      {
        id: 'q2',
        question: 'What is the elastic potential energy stored in a spring with k = 100 N/m stretched by x = 0.2 m?',
        options: ['20 Joules', '2 Joules', '10 Joules', '4 Joules'],
        correctIndex: 1,
        explanation: 'E_p = ½ k x² = 0.5 × 100 × (0.2)² = 50 × 0.04 = 2.0 Joules.',
      },
      {
        id: 'q3',
        question: 'In simple harmonic motion, when the mass passes through the equilibrium position (x = 0), what is its acceleration?',
        options: ['Zero', 'Maximum positive', 'Maximum negative', 'Undefined'],
        correctIndex: 0,
        explanation: 'Because F = -kx, when displacement x = 0, force F = 0, and by F = ma, acceleration a = 0.',
      },
    ],
    recommendedNextTopics: ['physics-wave-motion', 'physics-pendulum'],
    isImplemented: true,
  },
  {
    id: 'physics-wave-motion',
    title: 'Wave Motion, Superposition & Interference',
    subject: 'physics',
    topic: 'Waves & Optics',
    difficulty: 'Advanced',
    estimatedMinutes: 12,
    description: 'Examine transverse wave propagation and two-source interference. Control frequency, wavelength, wave speed (v = fλ), and witness constructive vs destructive interference.',
    learningObjectives: [
      'Demonstrate the fundamental wave relationship v = f · λ',
      'Observe the principle of wave superposition (y_total = y₁ + y₂)',
      'Identify constructive interference nodes and destructive anti-nodes',
      'Understand standing wave nodes and acoustic resonance',
    ],
    prerequisites: ['Trigonometric waves', 'Frequency & period'],
    explanation: {
      concept: 'A mechanical or electromagnetic wave transfers energy through a medium without net transport of matter.',
      whatWeChange: 'Frequency f (Hz), amplitude, wavelength λ, and phase angle between two interfering sources.',
      whatHappens: 'When peaks coincide (in-phase), amplitudes combine constructively. When peak meets trough, they cancel destructively.',
      whyItHappens: 'The wave equation is linear, so solutions add directly via linear superposition.',
      formula: 'v = f · λ  |  y(x,t) = A sin(kx - ωt)  |  Path diff Δx = mλ (constructive)',
      takeaway: 'Interference is the defining diagnostic hallmark of wave behavior, from sound to quantum electron waves.',
    },
    controls: [
      { id: 'frequency', label: 'Frequency (f)', min: 0.5, max: 4.0, step: 0.25, defaultValue: 1.5, unit: 'Hz' },
      { id: 'speed', label: 'Wave Speed (v)', min: 2, max: 20, step: 1, defaultValue: 10, unit: 'm/s' },
      { id: 'source2Phase', label: 'Source 2 Phase Shift', min: 0, max: 3.14, step: 0.15, defaultValue: 0, unit: 'rad' },
    ],
    questions: [
      {
        id: 'q1',
        question: 'If a wave has a frequency of 5 Hz and a wave speed of 20 m/s, what is its wavelength (λ)?',
        options: ['100 m', '4 m', '0.25 m', '15 m'],
        correctIndex: 1,
        explanation: 'v = f · λ → λ = v / f = 20 m/s / 5 Hz = 4.0 meters.',
      },
      {
        id: 'q2',
        question: 'When two identical waves meet with a phase difference of exactly π radians (180 degrees), what occurs?',
        options: ['Total constructive interference (amplitude doubles)', 'Total destructive interference (amplitude cancels to zero)', 'Frequency doubles', 'Wave speed becomes zero'],
        correctIndex: 1,
        explanation: 'Because sin(θ + π) = -sin(θ), the two waves have opposite signs and cancel each other out completely.',
      },
      {
        id: 'q3',
        question: 'In a standing wave, what are the stationary points with zero amplitude called?',
        options: ['Antinodes', 'Nodes', 'Crests', 'Harmonics'],
        correctIndex: 1,
        explanation: 'Nodes are points along a standing wave where displacement remains zero at all times due to destructive interference.',
      },
    ],
    recommendedNextTopics: ['math-trig-wave', 'physics-pendulum'],
    isImplemented: true,
  },

  // ==========================================
  // CHEMISTRY (1-5 Implemented + Planned)
  // ==========================================
  {
    id: 'chem-ph-scale',
    title: 'pH Scale & Acid-Base Equilibrium',
    subject: 'chemistry',
    topic: 'Acids & Bases',
    difficulty: 'Beginner',
    estimatedMinutes: 8,
    description: 'Experiment with hydrogen ion concentration [H⁺] across the 0–14 pH scale. Observe color changes in universal indicator, beaker molecular counts, and water autoionization (Kw).',
    learningObjectives: [
      'Understand the logarithmic definition of pH = -log₁₀[H⁺]',
      'Relate pH and pOH through the water ion-product Kw: pH + pOH = 14 at 25°C',
      'Identify universal indicator color shifts (red for acid, green for neutral, deep purple for base)',
      'Calculate hydronium [H₃O⁺] and hydroxide [OH⁻] molar concentrations',
    ],
    prerequisites: ['Logarithms base 10', 'Molar concentration (M)'],
    explanation: {
      concept: 'The pH scale measures how acidic or basic an aqueous solution is based on hydronium ion activity.',
      whatWeChange: 'Concentration of acid/base solute, volume, and solution classification (battery acid, coffee, water, bleach).',
      whatHappens: 'A 1-unit decrease in pH represents a 10-fold increase in [H⁺] ion concentration.',
      whyItHappens: 'The logarithmic scale compresses vast molarity ranges (from 1 M to 10⁻¹⁴ M) into an intuitive 0–14 metric.',
      formula: 'pH = -log₁₀[H⁺]  |  pOH = -log₁₀[OH⁻]  |  [H⁺][OH⁻] = 1.0 × 10⁻¹⁴',
      takeaway: 'Neutral water at 25°C has [H⁺] = [OH⁻] = 10⁻⁷ M, producing pH = 7.0.',
    },
    controls: [
      { id: 'ph', label: 'Target pH Value', min: 0, max: 14, step: 0.1, defaultValue: 7.0, unit: 'pH' },
      { id: 'volume', label: 'Beaker Volume', min: 0.1, max: 1.0, step: 0.05, defaultValue: 0.5, unit: 'L' },
    ],
    questions: [
      {
        id: 'q1',
        question: 'If a solution has a pH of 3, what is its hydrogen ion concentration [H⁺]?',
        options: ['0.001 M (10⁻³ M)', '0.003 M', '3.0 M', '10³ M'],
        correctIndex: 0,
        explanation: 'By definition [H⁺] = 10^(-pH) = 10^(-3) = 0.001 M.',
      },
      {
        id: 'q2',
        question: 'How many times more acidic is a solution with pH 4 compared to a solution with pH 6?',
        options: ['2 times', '20 times', '100 times (10²)', '1000 times'],
        correctIndex: 2,
        explanation: 'Each step on the logarithmic pH scale represents a factor of 10. A difference of 2 pH units is 10² = 100 times more concentrated in H⁺.',
      },
      {
        id: 'q3',
        question: 'What is the pOH of an alkaline solution whose pH is measured to be 11.5 at 25°C?',
        options: ['2.5', '3.5', '11.5', '14.0'],
        correctIndex: 0,
        explanation: 'At 25°C, pH + pOH = 14.0. Therefore, pOH = 14.0 - 11.5 = 2.5.',
      },
    ],
    recommendedNextTopics: ['chem-titration', 'chem-reaction-rate'],
    isImplemented: true,
  },
  {
    id: 'chem-gas-laws',
    title: 'Ideal Gas Law (PV = nRT) Kinetics',
    subject: 'chemistry',
    topic: 'Thermodynamics & Gases',
    difficulty: 'Intermediate',
    estimatedMinutes: 12,
    description: 'Compress, heat, and expand gas particles in a sealed piston cylinder. Test Boyle’s Law (P ∝ 1/V), Charles’s Law (V ∝ T), and Gay-Lussac’s Law (P ∝ T).',
    learningObjectives: [
      'Apply the Ideal Gas Law state equation PV = nRT in SI and atmospheric units',
      'Observe gas particle kinetic energy and wall collision frequency scaling with temperature',
      'Visualize Boyle’s inverse isothermal pressure-volume hyperbolic curves',
      'Distinguish absolute temperature in Kelvin from Celsius (T_K = T_C + 273.15)',
    ],
    prerequisites: ['Basic units: Pascal, Kelvin, Liters', 'Molecular concept'],
    explanation: {
      concept: 'Gases consist of microscopic particles in continuous random motion. Temperature is average kinetic energy.',
      whatWeChange: 'Piston volume V (L), gas temperature T (Kelvin), and molar quantity n (moles).',
      whatHappens: 'Decreasing volume forces particles into more frequent container wall collisions, driving up measured pressure.',
      whyItHappens: 'Pressure is force per unit area exerted by particle momentum transfers during elastic collisions with walls.',
      formula: 'P · V = n · R · T  |  R = 0.08206 L·atm/(mol·K) = 8.314 J/(mol·K)',
      takeaway: 'At constant temperature, halving volume doubles gas pressure (Boyle’s Law).',
    },
    controls: [
      { id: 'volume', label: 'Cylinder Volume (V)', min: 5, max: 40, step: 1, defaultValue: 20, unit: 'L' },
      { id: 'temperature', label: 'Temperature (T)', min: 100, max: 600, step: 10, defaultValue: 300, unit: 'K' },
      { id: 'moles', label: 'Amount of Gas (n)', min: 0.5, max: 5.0, step: 0.25, defaultValue: 1.0, unit: 'mol' },
    ],
    questions: [
      {
        id: 'q1',
        question: 'According to Boyle’s Law, if the volume of an ideal gas is halved while temperature is held constant, what happens to pressure?',
        options: ['Pressure is halved', 'Pressure doubles', 'Pressure quadruples', 'Pressure stays the same'],
        correctIndex: 1,
        explanation: 'P₁V₁ = P₂V₂. If V₂ = 0.5 V₁, then P₂ = 2 P₁.',
      },
      {
        id: 'q2',
        question: 'Why must temperature always be converted to Kelvin when using gas law equations?',
        options: ['Because Kelvin is based on absolute zero where thermal molecular motion ceases', 'Because Celsius has negative numbers that break ratios', 'Both A and B are correct', 'Kelvin makes the numbers smaller'],
        correctIndex: 2,
        explanation: 'Kinetic gas theory relies on absolute temperature where 0 K represents zero thermal kinetic energy.',
      },
      {
        id: 'q3',
        question: 'If a gas at 300 K is heated to 600 K in a rigid container of fixed volume, what happens to the pressure?',
        options: ['Pressure doubles (Gay-Lussac’s Law)', 'Pressure is cut in half', 'Pressure is unchanged', 'Volume expands anyway'],
        correctIndex: 0,
        explanation: 'At constant volume, P/T = constant. Doubling absolute temperature doubles particle speed squared, doubling pressure.',
      },
    ],
    recommendedNextTopics: ['chem-reaction-rate', 'physics-spring-mass'],
    isImplemented: true,
  },
  {
    id: 'chem-reaction-rate',
    title: 'Reaction Kinetics & Collision Theory',
    subject: 'chemistry',
    topic: 'Kinetics & Equilibrium',
    difficulty: 'Intermediate',
    estimatedMinutes: 12,
    description: 'Investigate how temperature, reactant concentration [A], and catalysts influence chemical reaction velocity and activation energy barriers (Arrhenius Law).',
    learningObjectives: [
      'Understand Collision Theory: reactions require sufficient kinetic energy and correct geometric orientation',
      'Analyze the Maxwell-Boltzmann molecular kinetic energy distribution curve',
      'Observe how catalysts lower activation energy (Ea) without being consumed',
      'Plot reactant decay and product accumulation concentration curves over time',
    ],
    prerequisites: ['Exothermic vs endothermic reactions', 'Chemical equations'],
    explanation: {
      concept: 'Chemical reaction rates depend on the frequency and energetic viability of molecular collisions.',
      whatWeChange: 'Temperature (Kelvin), initial reactant concentration [A], and catalyst presence.',
      whatHappens: 'Higher temperatures shift the Maxwell-Boltzmann curve rightward, drastically increasing the fraction of particles exceeding Ea.',
      whyItHappens: 'Catalysts provide an alternative reaction pathway with a lower activation energy barrier.',
      formula: 'Rate = k[A]ⁿ  |  Arrhenius Law: k = A · e^(-Ea / RT)',
      takeaway: 'As a rule of thumb in chemistry, a 10°C temperature rise roughly doubles the reaction rate.',
    },
    controls: [
      { id: 'temperature', label: 'Temperature', min: 280, max: 450, step: 5, defaultValue: 320, unit: 'K' },
      { id: 'concentration', label: 'Reactant [A]₀', min: 0.2, max: 3.0, step: 0.2, defaultValue: 1.0, unit: 'M' },
      { id: 'catalyst', label: 'Catalyst Efficiency', min: 0, max: 100, step: 10, defaultValue: 0, unit: '%' },
    ],
    questions: [
      {
        id: 'q1',
        question: 'How does adding a catalyst accelerate a chemical reaction?',
        options: ['By increasing the temperature of reactants', 'By lowering the activation energy barrier Ea', 'By increasing reactant concentration', 'By shifting the equilibrium constant Keq'],
        correctIndex: 1,
        explanation: 'A catalyst offers an alternate mechanistic pathway requiring lower activation energy, enabling more collisions to succeed.',
      },
      {
        id: 'q2',
        question: 'According to the Maxwell-Boltzmann distribution, what happens when temperature increases?',
        options: ['The peak shifts left and gets taller', 'The curve flattens and shifts right, dramatically increasing molecules with energy ≥ Ea', 'All molecules gain the exact same velocity', 'Activation energy is destroyed'],
        correctIndex: 1,
        explanation: 'Higher thermal energy broadens the distribution curve rightward, putting a much higher percentage of molecules above Ea.',
      },
      {
        id: 'q3',
        question: 'For a first-order reaction Rate = k[A], what happens to the instantaneous rate if concentration [A] is doubled?',
        options: ['The rate doubles', 'The rate quadruples', 'The rate remains unchanged', 'The rate drops by half'],
        correctIndex: 0,
        explanation: 'In a first-order reaction, rate is directly proportional to concentration: Rate ∝ [A].',
      },
    ],
    recommendedNextTopics: ['chem-titration', 'chem-ph-scale'],
    isImplemented: true,
  },
  {
    id: 'chem-titration',
    title: 'Acid-Base Titration & Equivalence Curves',
    subject: 'chemistry',
    topic: 'Quantitative Analysis',
    difficulty: 'Advanced',
    estimatedMinutes: 14,
    description: 'Perform a volumetric titration of hydrochloric acid (HCl) using sodium hydroxide (NaOH) from a burette. Monitor the sigmoidal pH curve and phenolphthalein color change.',
    learningObjectives: [
      'Identify the equivalence point where moles of acid equal moles of base (n_acid = n_base)',
      'Interpret the steep inflection region of a strong acid - strong base titration curve',
      'Observe phenolphthalein indicator transition from colorless (pH < 8.2) to vibrant pink (pH > 10.0)',
      'Calculate unknown analyte concentration using stoichiometric dilution C₁V₁ = C₂V₂',
    ],
    prerequisites: ['Molarity calculations', 'pH scale basics'],
    explanation: {
      concept: 'Titration is a laboratory method of quantitative chemical analysis to determine the concentration of an identified analyte.',
      whatWeChange: 'Burette titrant added volume (mL), base titrant concentration, and initial acid volume.',
      whatHappens: 'Near the equivalence point (V_eq = 25 mL), a single drop of titrant causes pH to spike rapidly from 4 to 10.',
      whyItHappens: 'Because pH is logarithmic, neutralizing the final trace micromoles of H⁺ causes an exponential drop in [H⁺] orders of magnitude.',
      formula: 'C_acid · V_acid = C_base · V_base (at 1:1 stoichiometric equivalence)',
      takeaway: 'The equivalence point of a strong acid - strong base titration is exactly pH 7.0.',
    },
    controls: [
      { id: 'addedVolume', label: 'Burette NaOH Added', min: 0, max: 50, step: 0.5, defaultValue: 10, unit: 'mL' },
      { id: 'acidConc', label: 'Acid Concentration', min: 0.05, max: 0.5, step: 0.05, defaultValue: 0.1, unit: 'M' },
    ],
    questions: [
      {
        id: 'q1',
        question: 'At the stoichiometric equivalence point of a strong acid (HCl) and strong base (NaOH) titration, what is the theoretical pH at 25°C?',
        options: ['pH 0', 'pH 7.0', 'pH 8.2', 'pH 14.0'],
        correctIndex: 1,
        explanation: 'Strong acid and strong base neutralize completely to form neutral water and salt (NaCl), giving an equivalence pH of 7.0.',
      },
      {
        id: 'q2',
        question: 'Why does phenolphthalein change color from clear to pink near the endpoint?',
        options: ['It reacts with atmospheric carbon dioxide', 'Its deprotonated conjugate base form has a conjugated electronic structure that absorbs green light, appearing pink', 'It evaporates', 'The temperature boils'],
        correctIndex: 1,
        explanation: 'Indicators are weak acids whose protonated and deprotonated forms have different chromophore light absorption spectra.',
      },
      {
        id: 'q3',
        question: 'If 25.0 mL of 0.10 M NaOH neutralizes 50.0 mL of unknown HCl solution, what is the concentration of the HCl?',
        options: ['0.050 M', '0.10 M', '0.20 M', '0.50 M'],
        correctIndex: 0,
        explanation: 'C_acid = (C_base × V_base) / V_acid = (0.10 M × 25 mL) / 50 mL = 0.050 M.',
      },
    ],
    recommendedNextTopics: ['chem-ph-scale', 'chem-atomic-structure'],
    isImplemented: true,
  },
  {
    id: 'chem-atomic-structure',
    title: 'Bohr Atomic Structure & Electron Shells',
    subject: 'chemistry',
    topic: 'Atomic & Quantum Physics',
    difficulty: 'Beginner',
    estimatedMinutes: 8,
    description: 'Construct elements on the periodic table by tuning proton, neutron, and electron counts. Observe shell configuration (2n²: 2, 8, 18), atomic mass, net charge, and isotopes.',
    learningObjectives: [
      'Relate proton count Z directly to elemental identity on the Periodic Table',
      'Calculate mass number A = protons + neutrons and identify nuclear isotopes',
      'Distinguish neutral atoms from cations (positive) and anions (negative)',
      'Fill electron energy levels according to the Aufbau rule and shell capacity 2, 8, 18',
    ],
    prerequisites: ['Basic subatomic particles (protons, neutrons, electrons)'],
    explanation: {
      concept: 'Atoms consist of a dense positive nucleus surrounded by quantized orbitals of negatively charged electrons.',
      whatWeChange: 'Number of protons (atomic number Z), neutrons (isotope mass), and orbital electrons.',
      whatHappens: 'Protons dictate the element (e.g., 6 = Carbon, 8 = Oxygen). Imbalance between protons and electrons creates an ion.',
      whyItHappens: 'Electrostatic Coulomb forces bind electrons to the nucleus, while quantum mechanics restricts electrons to quantized principal shells.',
      formula: 'Atomic Number Z = Protons  |  Mass A = P + N  |  Net Charge = P - E',
      takeaway: 'Chemical reactivity is largely dictated by valence electrons in the outermost electron shell.',
    },
    controls: [
      { id: 'protons', label: 'Protons (Atomic Number Z)', min: 1, max: 18, step: 1, defaultValue: 6, unit: '' },
      { id: 'neutrons', label: 'Neutrons (N)', min: 0, max: 22, step: 1, defaultValue: 6, unit: '' },
      { id: 'electrons', label: 'Electrons (e⁻)', min: 1, max: 18, step: 1, defaultValue: 6, unit: '' },
    ],
    questions: [
      {
        id: 'q1',
        question: 'Which subatomic particle strictly defines the elemental identity of an atom?',
        options: ['Number of electrons', 'Number of neutrons', 'Number of protons', 'Total atomic mass'],
        correctIndex: 2,
        explanation: 'The atomic number (number of protons) uniquely identifies which chemical element an atom is.',
      },
      {
        id: 'q2',
        question: 'If an atom has 8 protons and 10 electrons, what is its net electrostatic charge?',
        options: ['Neutral (0)', '+2 cation', '-2 anion', '+8'],
        correctIndex: 2,
        explanation: 'Net charge = Protons - Electrons = 8 - 10 = -2 (an oxide anion O²⁻).',
      },
      {
        id: 'q3',
        question: 'What is the maximum number of electrons that can occupy the innermost first electron shell (n = 1)?',
        options: ['2 electrons', '8 electrons', '18 electrons', '32 electrons'],
        correctIndex: 0,
        explanation: 'According to the 2n² quantum shell formula, the n = 1 shell holds at most 2(1)² = 2 electrons.',
      },
    ],
    recommendedNextTopics: ['chem-ph-scale', 'physics-ohms-law'],
    isImplemented: true,
  },

  // ==========================================
  // ROADMAP SIMULATIONS (PLANNED TOWARDS 150+)
  // Demonstrating the modular scalable architecture
  // ==========================================
  {
    id: 'math-matrix-operations',
    title: 'Matrix Transformations & Eigenvalues',
    subject: 'mathematics',
    topic: 'Linear Algebra',
    difficulty: 'Advanced',
    estimatedMinutes: 15,
    description: 'Visual 2D grid matrix warping, determinant scaling, rotation, shearing, and eigenvector invariance.',
    learningObjectives: ['Visualize 2x2 matrix vector transformations', 'Understand geometric determinant as area change'],
    prerequisites: ['Vectors and coordinate geometry'],
    explanation: { concept: 'Linear maps rotate and stretch space.', whatWeChange: 'Matrix elements', whatHappens: 'Grid shears', whyItHappens: 'Basis vector mapping', formula: 'T(v) = Av', takeaway: 'Matrices transform coordinate frames.' },
    controls: [],
    questions: [],
    recommendedNextTopics: ['math-vector-fields'],
    isImplemented: false,
  },
  {
    id: 'math-vector-fields',
    title: 'Vector Calculus & Gradient Flow',
    subject: 'mathematics',
    topic: 'Multivariable Calculus',
    difficulty: 'Advanced',
    estimatedMinutes: 15,
    description: 'Explore divergence, curl, line integrals, and 2D vector flow fields around source and vortex sinks.',
    learningObjectives: ['Interpret vector arrows in a Cartesian plane', 'Differentiate divergence vs curl'],
    prerequisites: ['Partial derivatives'],
    explanation: { concept: 'Vector fields assign vectors to points in space.', whatWeChange: 'Field equations', whatHappens: 'Flow alters', whyItHappens: 'Gradient operators', formula: '∇ · F, ∇ × F', takeaway: 'Key to electromagnetism and fluids.' },
    controls: [],
    questions: [],
    recommendedNextTopics: ['physics-electric-field'],
    isImplemented: false,
  },
  {
    id: 'math-circle-geometry',
    title: 'Circle Geometry & Chord Theorems',
    subject: 'mathematics',
    topic: 'Geometry',
    difficulty: 'Beginner',
    estimatedMinutes: 8,
    description: 'Inscribed angle theorem, tangents, chords, and secant segment power of a point.',
    learningObjectives: ['Inscribed angle is half the central angle', 'Tangent is perpendicular to radius'],
    prerequisites: ['Basic angles'],
    explanation: { concept: 'Circle symmetry creates invariant angle relationships.', whatWeChange: 'Arc angles', whatHappens: 'Subtended angle tracks', whyItHappens: 'Isosceles radial triangles', formula: 'θ_inscribed = ½ θ_central', takeaway: 'Fundamental to navigation and optics.' },
    controls: [],
    questions: [],
    recommendedNextTopics: ['math-trig-wave'],
    isImplemented: false,
  },
  {
    id: 'physics-electric-field',
    title: 'Coulomb’s Law & Electric Field Lines',
    subject: 'physics',
    topic: 'Electromagnetism',
    difficulty: 'Intermediate',
    estimatedMinutes: 12,
    description: 'Place positive and negative point charges to trace electric field vector contours and equipotential surfaces.',
    learningObjectives: ['Coulomb inverse square law F = kq₁q₂ / r²', 'Field lines point away from positive charges toward negative'],
    prerequisites: ['Vectors', 'Electrostatics'],
    explanation: { concept: 'Charges modify the surrounding space with an electric force field.', whatWeChange: 'Charge magnitudes', whatHappens: 'Field lines bend', whyItHappens: 'Superposition of E vectors', formula: 'E = kQ / r²', takeaway: 'Visualizes electrostatic forces.' },
    controls: [],
    questions: [],
    recommendedNextTopics: ['physics-capacitor'],
    isImplemented: false,
  },
  {
    id: 'physics-lens-optics',
    title: 'Geometric Optics: Thin Lens & Ray Tracing',
    subject: 'physics',
    topic: 'Waves & Optics',
    difficulty: 'Intermediate',
    estimatedMinutes: 10,
    description: 'Convex and concave lenses. Move object distance to observe real vs virtual, inverted vs upright images.',
    learningObjectives: ['Thin lens equation 1/f = 1/d_o + 1/d_i', 'Trace parallel, focal, and central light rays'],
    prerequisites: ['Law of refraction'],
    explanation: { concept: 'Curved glass bends light rays via Snell’s Law to form optical images.', whatWeChange: 'Focal length and object position', whatHappens: 'Image shifts magnification', whyItHappens: 'Refractive convergence', formula: '1/f = 1/d_o + 1/d_i', takeaway: 'Basis of cameras, microscopes, and vision.' },
    controls: [],
    questions: [],
    recommendedNextTopics: ['physics-wave-motion'],
    isImplemented: false,
  },
  {
    id: 'chem-electrochemistry',
    title: 'Galvanic Voltaic Cell & Nernst Equation',
    subject: 'chemistry',
    topic: 'Electrochemistry',
    difficulty: 'Advanced',
    estimatedMinutes: 15,
    description: 'Zinc-Copper Daniell cell. Watch electron transfer through the external wire and ion migration through the salt bridge.',
    learningObjectives: ['Standard cell potential E° = E°_cathode - E°_anode', 'Spontaneous redox electron driving force'],
    prerequisites: ['Redox oxidation states'],
    explanation: { concept: 'Chemical energy converts to electrical work via spontaneous oxidation-reduction reactions.', whatWeChange: 'Electrolyte concentrations', whatHappens: 'Voltage potential changes', whyItHappens: 'Nernst equation potential shifts', formula: 'E = E° - (RT/nF) ln Q', takeaway: 'Drives all modern chemical batteries.' },
    controls: [],
    questions: [],
    recommendedNextTopics: ['chem-reaction-rate'],
    isImplemented: false,
  },
];
