import { ExperimentLog, Badge } from '../types/analytics';
import { StudentProfile } from '../types/user';

export const INITIAL_STUDENT_PROFILE: StudentProfile = {
  id: 'student-alpha-01',
  name: 'Alex Mercer',
  email: 'alex.mercer@simulab.edu',
  avatar: '🧪',
  gradeLevel: 'Undergraduate STEM / AP Science',
  joinedDate: '2026-08-20',
  targetGoalHours: 15,
};

export const INITIAL_EXPERIMENT_LOGS: ExperimentLog[] = [
  {
    id: 'log-001',
    simulationId: 'physics-ohms-law',
    simulationTitle: "Ohm's Law & Circuit Dynamics",
    subject: 'physics',
    topic: 'Electricity & Circuits',
    difficulty: 'Beginner',
    timestamp: '2026-09-08T10:15:00Z',
    durationSeconds: 245,
    score: 92,
    accuracy: 94,
    attempts: 1,
    mistakesCount: 0,
    questionsAnswered: 3,
    passed: true,
  },
  {
    id: 'log-002',
    simulationId: 'chem-ph-scale',
    simulationTitle: 'pH Scale & Acid-Base Equilibrium',
    subject: 'chemistry',
    topic: 'Acids & Bases',
    difficulty: 'Beginner',
    timestamp: '2026-09-09T14:30:00Z',
    durationSeconds: 310,
    score: 88,
    accuracy: 90,
    attempts: 2,
    mistakesCount: 1,
    questionsAnswered: 3,
    passed: true,
  },
  {
    id: 'log-003',
    simulationId: 'math-linear-equation',
    simulationTitle: 'Linear Equations & Slope Analysis',
    subject: 'mathematics',
    topic: 'Algebra & Functions',
    difficulty: 'Beginner',
    timestamp: '2026-09-10T09:20:00Z',
    durationSeconds: 190,
    score: 95,
    accuracy: 100,
    attempts: 1,
    mistakesCount: 0,
    questionsAnswered: 3,
    passed: true,
  },
  {
    id: 'log-004',
    simulationId: 'physics-projectile',
    simulationTitle: 'Kinematic Projectile Motion',
    subject: 'physics',
    topic: 'Classical Mechanics',
    difficulty: 'Intermediate',
    timestamp: '2026-09-11T16:45:00Z',
    durationSeconds: 420,
    score: 82,
    accuracy: 80,
    attempts: 2,
    mistakesCount: 1,
    questionsAnswered: 3,
    passed: true,
  },
  {
    id: 'log-005',
    simulationId: 'math-quadratic',
    simulationTitle: 'Quadratic Equation Visualizer',
    subject: 'mathematics',
    topic: 'Quadratic Functions',
    difficulty: 'Intermediate',
    timestamp: '2026-09-12T11:10:00Z',
    durationSeconds: 380,
    score: 68,
    accuracy: 65,
    attempts: 3,
    mistakesCount: 2,
    questionsAnswered: 3,
    passed: true,
  },
  {
    id: 'log-006',
    simulationId: 'chem-gas-laws',
    simulationTitle: 'Ideal Gas Law (PV = nRT) Kinetics',
    subject: 'chemistry',
    topic: 'Thermodynamics & Gases',
    difficulty: 'Intermediate',
    timestamp: '2026-09-13T13:00:00Z',
    durationSeconds: 360,
    score: 90,
    accuracy: 92,
    attempts: 1,
    mistakesCount: 0,
    questionsAnswered: 3,
    passed: true,
  },
  {
    id: 'log-007',
    simulationId: 'math-trig-wave',
    simulationTitle: 'Trigonometric Wave & Phase Dynamics',
    subject: 'mathematics',
    topic: 'Trigonometry',
    difficulty: 'Intermediate',
    timestamp: '2026-09-14T15:25:00Z',
    durationSeconds: 450,
    score: 58,
    accuracy: 55,
    attempts: 3,
    mistakesCount: 3,
    questionsAnswered: 3,
    passed: false,
  },
  {
    id: 'log-008',
    simulationId: 'physics-pendulum',
    simulationTitle: 'Simple Harmonic Pendulum Oscillator',
    subject: 'physics',
    topic: 'Harmonic Motion',
    difficulty: 'Intermediate',
    timestamp: '2026-09-15T08:15:00Z',
    durationSeconds: 290,
    score: 86,
    accuracy: 85,
    attempts: 1,
    mistakesCount: 1,
    questionsAnswered: 3,
    passed: true,
  },
];

export const INITIAL_BADGES: Badge[] = [
  {
    id: 'badge-first-lab',
    title: 'First Experiment',
    description: 'Completed your very first STEM interactive simulation on SIMULAB.',
    icon: 'Sparkles',
    unlockedAt: '2026-09-08T10:18:00Z',
    isUnlocked: true,
    criteria: 'Complete 1 simulation',
  },
  {
    id: 'badge-physics-pioneer',
    title: 'Physics Pioneer',
    description: 'Executed 3 or more classical mechanics or circuit experiments.',
    icon: 'Zap',
    subject: 'physics',
    unlockedAt: '2026-09-15T08:20:00Z',
    isUnlocked: true,
    criteria: 'Complete 3 Physics experiments',
  },
  {
    id: 'badge-chemistry-alchemist',
    title: 'Molecular Alchemist',
    description: 'Conducted equilibrium and reaction kinetics experiments in chemistry.',
    icon: 'FlaskConical',
    subject: 'chemistry',
    unlockedAt: '2026-09-13T13:05:00Z',
    isUnlocked: true,
    criteria: 'Complete 2 Chemistry experiments',
  },
  {
    id: 'badge-math-apprentice',
    title: 'Calculus & Algebra Mind',
    description: 'Explored functions, equations, and wave mathematics visually.',
    icon: 'Sigma',
    subject: 'mathematics',
    unlockedAt: '2026-09-12T11:15:00Z',
    isUnlocked: true,
    criteria: 'Complete 3 Mathematics experiments',
  },
  {
    id: 'badge-perfect-score',
    title: 'Flawless Precision',
    description: 'Achieved 100% accuracy on all experimental verification questions in a session.',
    icon: 'Award',
    unlockedAt: '2026-09-10T09:23:00Z',
    isUnlocked: true,
    criteria: 'Score 100% accuracy in an experiment',
  },
  {
    id: 'badge-ten-sims',
    title: 'Lab Master (10 Completed)',
    description: 'Complete 10 interactive simulations across all three core disciplines.',
    icon: 'Trophy',
    isUnlocked: false,
    criteria: 'Complete 10 simulations in total',
  },
  {
    id: 'badge-streak-5',
    title: 'Consistent Inquirer',
    description: 'Maintain an active scientific study streak for 5 consecutive days.',
    icon: 'Flame',
    unlockedAt: '2026-09-15T08:15:00Z',
    isUnlocked: true,
    criteria: 'Log experiments across 5 days',
  },
];
